function [ROI_list]=Define_ROIs_paper_GSR(name_ROI_def)

%naming is very important: first three letters should correspond to
%network, further letters correspond to region
%regions should contain three or four letter, no more, no less
%DO NOT USE 'TOG' as network-name! (used to combine regions from different already-estimated networks)

if strcmp(name_ROI_def,'Smith')
    
    ROI_list={'SAL_ACC',[0 36 22];...     
        'SAL_lINS',[-36 12 -2];...
        'SAL_lMFG',[-28 54 14];...
        'SAL_rINS',[32 20 4];...
        'SAL_rMFG',[30 52 14];...
        'SMR_SMA',[0 -12 50];...       %%Paracentral lobe
        'SMR_lSMC',[-38 -26 56];...
        'SMR_rSMC',[44 -16 48];...
        'DMN_PRC',[2,-58,30];...      %%Precuneus/posteriorPCC        
        'DMN_lIPC',[-44,-60,24];...    %inferior parietal
        'DMN_mPFC',[2,56,-4];...
        'DMN_rIPC',[54,-62,28]};
end

end